### ISSUE TITLE
Can't check int value in dictionary

### ISSUE THREAD

**Issue by naoki-akimoto** [KiiPlatform/IoTCloud-iOSSDK#105]
ThingIFSDKTestsのXCTest+Utils.swift内で定義されているverifyDict(expectedDict:, actualData:)メソッド内でvalueがNSDictionaryだった場合のexpectedValueDictをDictionary<String, String>と固定して扱っているため、Dictionary<String, AnyObject>で定義し値にIntを持つようなケースではエラー扱いになってしまいます。

適切な担当者へ報告してください。

見つけた際の関連作業: https://github.com/KiiCorp/kiidocs/pull/2230/
ここのiOSの追記部分でmetadata内の値が3となっていたため判明。

**Comment by dairyo** [comment]
@naoki-akimoto 修正のPRを作成してみてもらえますか。あと、全てのテストを実行して問題ないかの確認もお願いします。

**Comment by naoki-akimoto** [comment]
@shinsuke-nara
こういう場合修正する前に仕様の確認をしないといけません。
このテスト群を設計、実装した人が、該当のメソッドではDictionary<String, String>しか扱わない、と定めたのかもしれません。
実際に今のように実装されているということは各テストケースでもDictionary<String, String>しか扱っていないはずです。
Stringしか要らないというなら修正は必要ありません。

**Comment by dairyo** [comment]
@naoki-akimoto テスト専用に特定の担当者がいるわけではありません。
このissueは改善提案だと認識しています。なので、PRを作成して提案をしようというわけです。

> 実際に今のように実装されているということは各テストケースでもDictionaryしか扱っていないはずです。
> Stringしか要らないというなら修正は必要ありません。

いまのテストは全て成功しているという認識です。なので、現状は十分なのでしょう。
改善の提案なので、修正自体に大きなコストがかからないならば、PRを作るという形で提案しようと考えています。
