### ISSUE TITLE
Implement cross thing trigger

### ISSUE THREAD

**Issue by dairyo** [KiiPlatform/IoTCloud-iOSSDK#149]
### 概要

今までのcommand triggerはstateをアップロードするthingと、triggerの結果、commandを受信するthingは同じものでなければなりませんでした。

サーバ側の実装が修正され、stateをアップロードするthingと、triggerの結果、commandを受信するthingを別のものにすることが可能になりました。このように別のthingにcommandを送信できるtriggerを`cross thing trigger`と呼びます。
### 修正について
#148 でAPIの修正を行いました。PRを確認してもらえれば分かりますが、targetとなるthingのTargetインスタンスを引数に追加しています。今までの`postNewTrigger`メソッドでは、targetを指定できなかったので、別のthingへのtriggerは作成できませんでした。この修正で別のthingの指定を可能にできます。

APIの修正に伴い、実装の修正とsmall testの作成をお願いします。large testの実装は不要です。代わりに、thing-if-ThingSDKのサンプルアプリを利用し、手動でcross thing triggerが実行できることを確認してください。

実装のPRはcross_thing_triggerブランチに対して出すようにしてください。
### テストについて

上でも記載しましたが、large testは不要です。small testと手動の確認をお願いします。

手動での確認については、KiiCorp/iot-cloud-api#67 でcross thing triggerを実行できない件がissueとしてあげられています。この概要にcurlを使った確認手順が記載されています。手順3. の`Create trigger`の部分をthing-if-iOSSDKで行うようにすれば確認ができます。参考にしてください。
### 参考資料

triggerの登録のREST APIの詳細については[hing-IF REST API Documentation](http://docs.kii.com/thing-if-rest/)で確認してください。

また、仕様の詳細についてはgoogle docs内の資料で確認してください。
Related PR: #148

**Comment by satoshikumano** [comment]
Done
