### ISSUE TITLE
postNewTrigger and patchTrigger may lack target in Command

### ISSUE THREAD

**Issue by dairyo** [KiiPlatform/IoTCloud-iOSSDK#156]
In specification, target field in Command for postNewTrigger and patchTrigger request is mandatory field but, in SDK, the target is optional.

I think this is specification bug or implementation bug. We need to check whether is correct and fix it.

**Comment by naoki-akimoto** [comment]
サンプルアプリを使用してcommantTarget指定無しでpatchTriggerした際の通信ログです。
送信したコマンド内に `target` が存在しなくともアップデート成功(204)が返されているのがわかります。

### リクエスト

 <NSMutableURLRequest: 0x7feb49f1f830> { URL: https://api-jp.kii.com/thing-if/apps/a4c6c6a7/targets/thing:th.5a8848a00022-734b-5e11-97d9-0dd75f63/triggers/0d9ee400-9d8b-11e5-9b7b-22000a808d3d }

### リクエストボディ

 Optional({
　"command": {
　　"schema":"SmartLightDemo",
　　"actions":[{"turnPower":{"power":true}}],
　　"issuer":"user:9980daa00022-90c8-6e11-13f6-05b34cbd",
　　"schemaVersion":1},
　"triggersWhat":"COMMAND"})

### レスポンス

 Optional(<NSHTTPURLResponse: 0x7feb49c5aa70> { URL: https://api-jp.kii.com/thing-if/apps/a4c6c6a7/targets/thing:th.5a8848a00022-734b-5e11-97d9-0dd75f63/triggers/0d9ee400-9d8b-11e5-9b7b-22000a808d3d } { status code: 204, headers {
    "Accept-Ranges" = bytes;
    "Access-Control-Allow-Origin" = "*";
    "Access-Control-Expose-Headers" = "Content-Type, Authorization, Content-Length, X-Requested-With, ETag, X-Step-Count, X-HTTP-Status-Code";
    Age = 0;
    "Cache-Control" = "max-age=0, no-cache, no-store";
    Connection = "keep-alive";
    Date = "Fri, 09 Sep 2016 09:33:01 GMT";
    Server = openresty;
} })

**Comment by dairyo** [comment]
秋元さんのコメントに補足をします。

post new triggerとpatch triggerの両方のAPIでcommand内のtarget fieldは省略可となっています。
post new trigger、patch triggerともに省略した場合は、triggerのthingのIDがtargetに利用されます。

このため、cross thing triggerの状態でtargetを省略してpatch triggerを行うと、targetが、他のthingからtriggerのthingに変更されてしまいます。

**Comment by dairyo** [comment]
この実装の修正は、新しいpostNewTriggerの実装とともに行います。
