### ISSUE TITLE
Release v0.13.0

### ISSUE THREAD

**Issue by dairyo** [KiiPlatform/IoTCloud-iOSSDK#178]
### New feature
- Data grouping interval (#146)
- Cross thing command trigger and optional fields (#164)
- Optional fields for server code trigger (#167)
### Improvement
- Request error handling (#144)
- Convert to swift2.3 (#159)
- Change unmodifiable var properties to let. (#166)
### Note
- backward compatibility
  - Properties in `ServerCode` class became let. Applications can only set properties with initializer.

Related PR: #177

**Comment by satoshikumano** [comment]
released.
