### ISSUE TITLE
API change proposal for v1.0.0

### ISSUE THREAD

**Issue by dairyo** [KiiPlatform/IoTCloud-iOSSDK#204]
thing-if iOSSDK v1.0.0に向けて、APIの修正提案を行います。修正提案は以下の通りです。

  * NS系クラスをSwiftネイティブなデータ型に変更
  * API命名規約のチェック
  * 機能が重複しているAPIの削除
  * 不要な暗黙的オプショナルプロパティを削除

以下に各項目の詳細を記載します。

### NS系クラスをSwiftネイティブなデータ型に変更

`func toNSDictionary() -> NSDictionary` メソッドなど、戻り値や引数にNS系クラスのインスタンスを受渡しするメソッドやプロパティが存在しています。SwiftネイティブなライブラリならばNS系クラスは出来る限り使用せず、Swiftのデータ型に置き換えて行った方が良いと思われます。

現在確認出来ているNS系のクラスは以下の3つです。

  * NSDictionary
  * NSNumber
  * NSError

### API命名規約のチェック

swiftの一般的なAPI命名規約をチェックし、thing-if iOSSKがその規約に従っているかチェックします。
規約に従っていないものについては規約に従う形に変更した方が、より一般的な命名になるとおもわれます。

特にenumerationについては、v0.13.1までのThingIFSDKでは要素名に大文字とアンダースコアを利用していました。swift3.0への自動コンバートの結果、これらは小文字に変更されました。

swift 3.0でのAppleの推奨形式を調査し、その形式に揃えた方がよいと思われます。

  * 参考HP
    * [API Design Guidelines](https://swift.org/documentation/api-design-guidelines/)
    * [AppleのEnumerationの説明ページ](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Enumerations.html#//apple_ref/doc/uid/TP40014097-CH12-ID145)
    * [raywenderlich.comのガイドライン](https://github.com/raywenderlich/swift-style-guide#enumerations)
  * 関連issue: #205

### 機能が重複しているAPIの削除

`ThingIFAPI#postNewTrigger()` などは機能拡張のため、同名の新しいAPIを追加しました。新しく作成されたAPIは既存のAPIの機能を包含しています。

v1.0.0に向けて、SDKをよりシンプルにする為に重複した機能は削除してもよいのではと考えています。

### 不要な暗黙的オプショナルプロパティを削除

#198 で`ThingIFAPI`クラスのプロパティを暗黙的オプショナルから値型へ変更しました。変更したものはそもそも値型で良いものが、暗黙的オプショナルになっていたためです。

同様の問題を持つプロパティがあるならば、修正しておくべきだと考えます。

**Comment by dairyo** [comment]
@satoshikumano 
v1.0.0に向けての修正提案です。詳細な作業内容は各項目ごとに掘り下げていきます。
まずは、大枠として必要かどうかを話し合えればと思っています。

確認よろしくお願いします。

**Comment by satoshikumano** [comment]
> NS系クラス

具体的なクラス名を列挙してもらえますか。

**Comment by dairyo** [comment]
@satoshikumano 

概要に具体的なクラスを追加しました。現在のところ確認出来ているのは以下の2つです。
- NSDictionary
- NSNumber

**Comment by dairyo** [comment]
@satoshikumano 

NSErrorも追加しました。ThingIFErrorの中で使われています。

**Comment by satoshikumano** [comment]
@shinsuke-nara 
NSDictionary, NSNumber, NSError を何に置き換えるのか、置き換えた場合の影響は何なのかを調査してください。
