### ISSUE TITLE
Check adaptability for API design guideline.

### ISSUE THREAD

**Issue by dairyo** [KiiPlatform/IoTCloud-iOSSDK#205]
To update thing-if iOSSDK to version 1.0.0, we check whether our API is adapted to API design guideline.

As API design guideline, We use [this document](https://swift.org/documentation/api-design-guidelines/).

Related issue: #204

**Comment by dairyo** [comment]
I read API design guideline. As as result, We should fix API according to following points:

### Omit needless words
- Builder classes have setter methods like `APIBuilder.setPort(_:)`. In this case, `Port` is needless word. We should remove them. Removing setter itself and adding them to initializer is another solution.
- Following 2 methos can be `ThingIFAPI.onboardWith()`, If first argumet does not ommit.
  - `ThingIFAPI.onboardWithVendorThingID(_:thingPassword:options:completionHandler:)`
  - `ThingIFAPI.onboardWithThingID(_:thingPassword:options:completionHandler:)`
- `ThingIFAPI.onboardEndnodeWithGateway(_:endnodePassword:options:completionHandler:)` can be `ThingIFAPI.onboard(_:endnodePassword:options:completionHandler:)`
- Following 2 methods can be  `GatewayAPI.list()` because, listed items are presented with completionHandler.
  - `GatewayAPI.listPendingEndNodes(_:)`
  - `GatewayAPI.listOnboardedEndNodes(_:)`

### Begin names of factory methods with “make”
- `toNSDictionary()` like `Clause.toNSDictionary()` should be changed to `makeDictionary()`
- Builder classes have `build()` method like `AppBuilder.build()`. They might be changed to `makeXXX` like `AppBuilder.makeApp()`

### Name functions and methods according to their side-effects

Methods to get information from server does not side effects. So such methods can be renamed to noun style.

For example, `ThingIFAPI.listCommands()` can be changed ato `ThingIFAPI.listedCommands()`

**Comment by dairyo** [comment]
熊野さんとの話し合いの結果、`Name functions and methods according to their side-effects` の部分は変更しないことになりました。

**Comment by satoshikumano** [comment]
@shinsuke-nara 

> 熊野さんとの話し合いの結果、Name functions and methods according to their side-effects の部分は変更しないことになりました。

少し結論が曖昧なまま議論が終わってしまったと思います。
少なくともREST APIを呼び出す部分については動詞のままで良い。という結論になったと記憶しています。

改めて見直してみると、REST APIをコールするメソッドに関してはside-effectsがあるので動詞のままで良い と考えた方がしっくりきますね。
(POSTだろうがGETだろうがside-effectsがあるとみなす。print()の例を考えると妥当かと思います。)

side-effectsに関しては定義がはっきりしないので、以下のようにしたいと思います。
- mutating vs non-mutating に関してはガイドラインに従う。
- REST APIの呼び出しは内容に関わらずside-effectありと考える。
- その他のside-effectsについては個別に見る

その他のside-effectsに何があるのか、確認お願いします。
