### ISSUE TITLE
change NS classes to Swift native classes.

### ISSUE THREAD

**Issue by naoki-akimoto** [KiiPlatform/IoTCloud-iOSSDK#218]
API部分で使用しているNS**クラスをSwiftのクラスに置き換えることを検証し可能なら置き換えてください。

現在置き換えを想定しているクラスは以下です。
* NSDictionary
* NSNumber
* NSError

まず、これらをSwiftのどのクラスに置き換えるか、置き換えた場合の影響について調査してください。

No.1005
Related #204

**Comment by naoki-akimoto** [comment]
NSDictionaryからDictionaryへの変更は[ブリッジがある](https://developer.apple.com/reference/swift/dictionary)ので特に問題は無い。
ただNSDictionaryを返すメソッドがほとんどtoNSDictionaryなので名前を変える必要がある。

**Comment by dairyo** [comment]
@naoki-akimoto `toNSDictionary`というメソッド名については、`makeDictionary`に変更する予定です。こちらの作業でメソッド名の変更まで行っていただいた方が良いかと思います。

**Comment by naoki-akimoto** [comment]
NSErrorに関してはインスタンスを作成している箇所があるので、Errorプロトコルを実装したenumを用意する必要がありそう。ただし、ThingIFErrorに追加する場合、ThingIFError.errorRequestの引数がThingIFError内に定義されることになるので多少戸惑うかもしれない。
作成するenumはcode(OperationErrorCode)とuserInfo(Dictionary、省略可)を持ては十分と思われる。

また、NSErrorはErrorをextensionしているので型変換などは特に問題ないはず。

**Comment by naoki-akimoto** [comment]
NSNumberに関してはそのほとんどがNS[Mutable]Dictionaryへの値部分の出し入れや値の型判定に使われているため、Dictionaryへの置き換えと共に要らなくなると思われる。
型判定はどのフィールドかによって既にRest APIで決まっていることなのでNSNumberで入れる必要も取る必要も無い。
一ケ所テストでArrayからas NSNumberで値を取り出すところがあるが、これも元をたどるとNSDictionaryにたどり着くので値の型判定と同じ。

**Comment by naoki-akimoto** [comment]
NS[Mutable]DictionaryからDictionaryへのキャストだとSwiftコンパイラがSeg11を吐いて落ちるようです。内部でディクショナリー作ってる部分も修正が必要なようです。

**Comment by dairyo** [comment]
修正が完了したのでcloseします。
