### ISSUE TITLE
ビルドに必要なソフトウェアの一覧を更新してください

### ISSUE THREAD

**Issue by ykomano** [KiiPlatform/IoTCloud-iOSSDK#247]
README.mdを参考にmasterブランチのMakefileを実行しようとしましたが、Requirementsに不足があるのでドキュメントのビルドで止まりました

- jazzyが必要である
- jazzyが依存しているxcodeprojがCFPropertyListとnanaimoに依存している

**Comment by satoshikumano** [comment]
96975835685aecae1cb4d1e1501f446a3d3165ee
ルートのREADMEはアプリの開発者向けなので、ThingIFSDK/README.mkdを追加しSDKの開発者向けのビルド手順を記載しました。

**Comment by ykomano** [comment]
ありがとうございました
