### ISSUE TITLE
Condition description.

### ISSUE THREAD

**Issue by satoshikumano** [KiiPlatform/IoTCloud-iOSSDK#25]
Condition description DSL has been changed and lets follow new DSL.

Changes:
- 'Statement' is changed to 'Clause'
- Supported Operators are changed from [ '=', '!=', "<", "<=", ">", ">=", "And", "Or"] to ["Equals", "NotEquals", "Range", "And", "Or"]

**Comment by yongpingchen** [comment]
<img width="612" alt="screen shot 2015-08-24 at 11 36 00 am" src="https://cloud.githubusercontent.com/assets/1248696/9431854/5a606ae6-4a54-11e5-89ed-9c883a6f921c.png">

**Comment by yongpingchen** [comment]
The PR to fix this issue https://github.com/KiiPlatform/IoTCloud-iOSSDK/pull/28
