### ISSUE TITLE
SDK improvement lists

### ISSUE THREAD

**Issue by yongpingchen** [KiiPlatform/IoTCloud-iOSSDK#33]
- [ ] SDK needs schema for validating actions, status and etc.
- [ ] Provide public readonly attributes of Clauses
  - [ ] field, value of EqualsClause
  - [ ] equalClause of NotEqualsClause
  - [ ] field, lowerLimit, lowerIncluded, upperLimit and upperIncluded of RangeClause

**Comment by satoshikumano** [comment]
Won't manage lists here.
